apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "webserver.default.svc"
webhooks:
- name: "webserver.default.svc"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "default"
      name: "webserver"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lKQU5YMU1WT1FodUJ2TUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0F4SGpBY0JnTlYKQkFNTUZYZGxZbk5sY25abGNpNWtaV1poZFd4MExuTjJZekFlRncweU1UQXhNamt3TnpNek1qRmFGdzAwT0RBMgpNVFl3TnpNek1qRmFNQ0F4SGpBY0JnTlZCQU1NRlhkbFluTmxjblpsY2k1a1pXWmhkV3gwTG5OMll6Q0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOc0pwbzEySVBVRUZ0WFBFVURFcXhGZ0VTVW4Kc240OURSQkJhVkZlSTgzLzI0bHpJTUY3MkxGWGEyUU54UEZKcjZ5amxlMEIxaSsxUEgyaUlNMGdwRmZwbklBVgpXY2VrYmU0OTRzYnFZanNNMWFya0FpcE02T0lCR091NzJJQml0SmZzd3p5WUp4SytPMzZTWDh3UEo2UUR1SVVpClRUNmVvTlhVUCsrYTdnVDhIV0tOeHdWL2hwRmNDOFJYblZQWHR6OFBKckdKWjhlR1VBcVBNdDNoQXNyaTRSM2QKMGpCWnhIdUozc2hJSUl5VEozc3p2cHZHSXdhUDBUYVppMHFabU1wbldiZk1sNHl2cWgyNEZhVHR1ZjZGbTJESAp3ZVNJeGtBRWQrZUk0STJreGhHZjB5bFJUNFpscUU0aEd4NTl2K2RjWDJld2sxaHcxQUs1MmlBU2ViOENBd0VBCkFhTlFNRTR3SFFZRFZSME9CQllFRk0rQktDUzNUOXdIdkdHWVpIcGRoWFltbG5aTk1COEdBMVVkSXdRWU1CYUEKRk0rQktDUzNUOXdIdkdHWVpIcGRoWFltbG5aTk1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFGQ1dzVXBBaFhyaEt0NUthUmx1djh6R3FHRytSWENYUkhReWwrdmZZS25IcHQxeUdHcUxrVUFjCklDcFNyajJSMnBzYytQeXRPRkFCNTYwMVd1MW5TYkFjeWpNNUpleHh3K2hVVU4vZzVqaVJHNzFWZk9IeWJLSCsKVGxEUnlXMXg4NHl1MHVFVnlOd1JkU0tGK0s5T1J4cGl3b3lrWm8xalFFWXVyQmhJdk5ob2llQi9CRGZwK3NhMApKMyt2WWdKZzhqTitGcjJsM0MxYTdzdjMzdnRNU2p1MEZyaktaK21hejVpaDRyVFhxWlpGOXU5S05IQ253ejlhClE3NUhyeDJHbmdxb0VxYnhzaDR4V0VkUzdCem5KTFVrdGlTOWllOXVNZS8yUnp5U3VyQWszcUFXeUJJVStQTkEKK0cyUkx0dnZ1aGhtQytzTmNiNy83NDN2RGFsWjdUND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
